In [1]:
import torch

In [139]:
embedding = torch.nn.Embedding(6, 3, padding_idx=2)

In [140]:
input = torch.LongTensor([[0,2,0,5], [1,2,3,4]])

In [141]:
# (number of words in a seq) x (number of seq in a batch)
# 4 2-word sequences 
input.size()

torch.Size([2, 4])

In [142]:
# token id of the 0-th word of the 3-rd source sequence
input[0, 3]

tensor(5)

In [146]:
x = embedding(input)

In [147]:
x

tensor([[[-0.3574,  0.1658,  2.3912],
         [ 0.0000,  0.0000,  0.0000],
         [-0.3574,  0.1658,  2.3912],
         [ 0.6276, -0.6319,  0.5069]],

        [[ 0.8635, -0.2714, -0.8179],
         [ 0.0000,  0.0000,  0.0000],
         [-0.1126,  0.2189,  0.7983],
         [ 1.0659,  0.5744, -1.0153]]], grad_fn=<EmbeddingBackward>)

In [144]:
embedding(input).size()

torch.Size([2, 4, 3])

In [150]:
# input vector (word embedding) of the 1-st word in the 2-nd source seq of this batch
x[1, 2, :]

tensor([-0.1126,  0.2189,  0.7983], grad_fn=<SliceBackward>)

In [145]:
input[0, 1]

tensor(2)

In [62]:
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

In [106]:
seq = torch.tensor([[1,2,0], [3,0,0], [4,5,6]])

In [107]:
lens = [2, 1, 3]

In [108]:
packed = pack_padded_sequence(seq, lens, batch_first=True, enforce_sorted=False)

In [109]:
packed

PackedSequence(data=tensor([4, 1, 3, 5, 2, 6]), batch_sizes=tensor([3, 2, 1]), sorted_indices=tensor([2, 0, 1]), unsorted_indices=tensor([1, 2, 0]))

In [110]:
seq_unpacked, lens_unpacked = pad_packed_sequence(packed, batch_first=True, padding_value=0.01)

In [111]:
seq_unpacked

tensor([[1, 2, 0],
        [3, 0, 0],
        [4, 5, 6]])

In [112]:
lens_unpacked

tensor([2, 1, 3])

In [95]:
f_len = torch.zeros((5, ))

In [97]:
f_len.size()[0]

5

In [98]:
h0 = torch.randn(2, 3, 20)

In [101]:
h0.size()

torch.Size([2, 3, 20])

In [113]:
print("hello world")

hello world


In [114]:
embedding

Embedding(6, 3, padding_idx=2)

In [119]:
input2 = torch.LongTensor([[0,2,0,5], [1,2,3,4], [0,3,2,4]])

In [121]:
input2.shape

torch.Size([3, 4])

In [124]:
embedding2 = embedding(input2)

In [125]:
embedding2.shape

torch.Size([3, 4, 3])