In [1]:
import torch

In [139]:
embedding = torch.nn.Embedding(6, 3, padding_idx=2)

In [140]:
input = torch.LongTensor([[0,2,0,5], [1,2,3,4]])

In [141]:
# (number of words in a seq) x (number of seq in a batch)
# 4 2-word sequences 
input.size()

torch.Size([2, 4])

In [142]:
# token id of the 0-th word of the 3-rd source sequence
input[0, 3]

tensor(5)

In [146]:
x = embedding(input)

In [147]:
x

tensor([[[-0.3574,  0.1658,  2.3912],
         [ 0.0000,  0.0000,  0.0000],
         [-0.3574,  0.1658,  2.3912],
         [ 0.6276, -0.6319,  0.5069]],

        [[ 0.8635, -0.2714, -0.8179],
         [ 0.0000,  0.0000,  0.0000],
         [-0.1126,  0.2189,  0.7983],
         [ 1.0659,  0.5744, -1.0153]]], grad_fn=<EmbeddingBackward>)

In [144]:
embedding(input).size()

torch.Size([2, 4, 3])

In [150]:
# input vector (word embedding) of the 1-st word in the 2-nd source seq of this batch
x[1, 2, :]

tensor([-0.1126,  0.2189,  0.7983], grad_fn=<SliceBackward>)

In [145]:
input[0, 1]

tensor(2)

In [62]:
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

In [106]:
seq = torch.tensor([[1,2,0], [3,0,0], [4,5,6]])

In [107]:
lens = [2, 1, 3]

In [108]:
packed = pack_padded_sequence(seq, lens, batch_first=True, enforce_sorted=False)

In [109]:
packed

PackedSequence(data=tensor([4, 1, 3, 5, 2, 6]), batch_sizes=tensor([3, 2, 1]), sorted_indices=tensor([2, 0, 1]), unsorted_indices=tensor([1, 2, 0]))

In [110]:
seq_unpacked, lens_unpacked = pad_packed_sequence(packed, batch_first=True, padding_value=0.01)

In [111]:
seq_unpacked

tensor([[1, 2, 0],
        [3, 0, 0],
        [4, 5, 6]])

In [112]:
lens_unpacked

tensor([2, 1, 3])

In [95]:
f_len = torch.zeros((5, ))

In [97]:
f_len.size()[0]

5

In [98]:
h0 = torch.randn(2, 3, 20)

In [101]:
h0.size()

torch.Size([2, 3, 20])

In [113]:
print("hello world")

hello world


In [114]:
embedding

Embedding(6, 3, padding_idx=2)

In [119]:
input2 = torch.LongTensor([[0,2,0,5], [1,2,3,4], [0,3,2,4]])

In [121]:
input2.shape

torch.Size([3, 4])

In [124]:
embedding2 = embedding(input2)

In [125]:
embedding2.shape

torch.Size([3, 4, 3])

In [156]:
x = torch.randn(2, 3)

In [157]:
x

tensor([[ 0.7632, -0.2594, -0.3653],
        [ 0.5253, -1.6801,  0.0770]])

In [160]:
torch.cat((x, x), 0)

tensor([[ 0.7632, -0.2594, -0.3653],
        [ 0.5253, -1.6801,  0.0770],
        [ 0.7632, -0.2594, -0.3653],
        [ 0.5253, -1.6801,  0.0770]])

In [239]:
h = torch.randn(5, 6, 3)

In [240]:
h

tensor([[[-0.7048, -1.4103, -0.3151],
         [ 0.1557, -0.9740, -1.2117],
         [-1.1848, -0.6721, -1.0202],
         [ 1.4864, -1.0039, -0.9150],
         [ 1.1800,  1.6672, -1.4563],
         [-2.1326,  0.0324,  0.7923]],

        [[-2.2260,  1.0418,  1.5708],
         [ 0.0851,  0.8733, -0.7298],
         [ 0.2577, -0.4051, -1.4668],
         [ 0.1813, -1.8326, -0.6667],
         [ 0.6792, -0.0127, -0.0126],
         [ 0.4779, -1.7250, -0.1287]],

        [[-1.1724, -0.3274,  0.0574],
         [ 0.2483,  1.5302,  0.3711],
         [-0.8765, -1.6281, -1.0314],
         [ 0.0530,  1.1504, -1.2002],
         [-0.2686,  1.2466,  2.3522],
         [ 1.5607, -2.9683,  0.2349]],

        [[-0.8316, -1.1493,  0.0612],
         [ 1.2385,  0.5432,  0.1464],
         [ 0.1538,  1.5263, -0.2739],
         [ 1.1321, -0.5144,  1.8355],
         [ 0.5592,  0.4163,  1.7067],
         [ 2.5304, -1.0066,  0.2032]],

        [[ 0.9103, -0.8966,  0.8245],
         [-0.0280,  1.5550,  0.5115],
    

In [241]:
h[2:, 1].shape

torch.Size([3, 3])

In [242]:
h[2, 1].shape

torch.Size([3])

In [243]:
h[3, 0].reshape(1, 3).shape

torch.Size([1, 3])

In [244]:
torch.cat((h[3, 0].reshape(1, 3), h[2, 1].reshape(1, 3), h[2, 2].reshape(1, 3), h[4, 3].reshape(1, 3)), 0).shape

torch.Size([4, 3])

In [245]:
f_lens = [3, 2, 4, 1, 2, 3]

In [248]:
cat_list = [h[f_lens[m], m].reshape(1, 3) for m in range(6)]

In [252]:
forward = torch.cat(cat_list, 0)

In [253]:
forward.shape

torch.Size([6, 3])

In [255]:
backward = h[0]

In [256]:
backward.shape

torch.Size([6, 3])

In [258]:
torch.cat((forward, backward), 1).shape

torch.Size([6, 6])