In [1]:
import torch

In [139]:
embedding = torch.nn.Embedding(6, 3, padding_idx=2)

In [140]:
input = torch.LongTensor([[0,2,0,5], [1,2,3,4]])

In [141]:
# (number of words in a seq) x (number of seq in a batch)
# 4 2-word sequences 
input.size()

torch.Size([2, 4])

In [142]:
# token id of the 0-th word of the 3-rd source sequence
input[0, 3]

tensor(5)

In [146]:
x = embedding(input)

In [147]:
x

tensor([[[-0.3574,  0.1658,  2.3912],
         [ 0.0000,  0.0000,  0.0000],
         [-0.3574,  0.1658,  2.3912],
         [ 0.6276, -0.6319,  0.5069]],

        [[ 0.8635, -0.2714, -0.8179],
         [ 0.0000,  0.0000,  0.0000],
         [-0.1126,  0.2189,  0.7983],
         [ 1.0659,  0.5744, -1.0153]]], grad_fn=<EmbeddingBackward>)

In [144]:
embedding(input).size()

torch.Size([2, 4, 3])

In [150]:
# input vector (word embedding) of the 1-st word in the 2-nd source seq of this batch
x[1, 2, :]

tensor([-0.1126,  0.2189,  0.7983], grad_fn=<SliceBackward>)

In [145]:
input[0, 1]

tensor(2)

In [62]:
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

In [106]:
seq = torch.tensor([[1,2,0], [3,0,0], [4,5,6]])

In [107]:
lens = [2, 1, 3]

In [108]:
packed = pack_padded_sequence(seq, lens, batch_first=True, enforce_sorted=False)

In [109]:
packed

PackedSequence(data=tensor([4, 1, 3, 5, 2, 6]), batch_sizes=tensor([3, 2, 1]), sorted_indices=tensor([2, 0, 1]), unsorted_indices=tensor([1, 2, 0]))

In [110]:
seq_unpacked, lens_unpacked = pad_packed_sequence(packed, batch_first=True, padding_value=0.01)

In [111]:
seq_unpacked

tensor([[1, 2, 0],
        [3, 0, 0],
        [4, 5, 6]])

In [112]:
lens_unpacked

tensor([2, 1, 3])

In [95]:
f_len = torch.zeros((5, ))

In [97]:
f_len.size()[0]

5

In [98]:
h0 = torch.randn(2, 3, 20)

In [101]:
h0.size()

torch.Size([2, 3, 20])

In [113]:
print("hello world")

hello world


In [114]:
embedding

Embedding(6, 3, padding_idx=2)

In [119]:
input2 = torch.LongTensor([[0,2,0,5], [1,2,3,4], [0,3,2,4]])

In [121]:
input2.shape

torch.Size([3, 4])

In [124]:
embedding2 = embedding(input2)

In [125]:
embedding2.shape

torch.Size([3, 4, 3])

In [156]:
x = torch.randn(2, 3)

In [157]:
x

tensor([[ 0.7632, -0.2594, -0.3653],
        [ 0.5253, -1.6801,  0.0770]])

In [160]:
torch.cat((x, x), 0)

tensor([[ 0.7632, -0.2594, -0.3653],
        [ 0.5253, -1.6801,  0.0770],
        [ 0.7632, -0.2594, -0.3653],
        [ 0.5253, -1.6801,  0.0770]])

In [239]:
h = torch.randn(5, 6, 3)

In [240]:
h

tensor([[[-0.7048, -1.4103, -0.3151],
         [ 0.1557, -0.9740, -1.2117],
         [-1.1848, -0.6721, -1.0202],
         [ 1.4864, -1.0039, -0.9150],
         [ 1.1800,  1.6672, -1.4563],
         [-2.1326,  0.0324,  0.7923]],

        [[-2.2260,  1.0418,  1.5708],
         [ 0.0851,  0.8733, -0.7298],
         [ 0.2577, -0.4051, -1.4668],
         [ 0.1813, -1.8326, -0.6667],
         [ 0.6792, -0.0127, -0.0126],
         [ 0.4779, -1.7250, -0.1287]],

        [[-1.1724, -0.3274,  0.0574],
         [ 0.2483,  1.5302,  0.3711],
         [-0.8765, -1.6281, -1.0314],
         [ 0.0530,  1.1504, -1.2002],
         [-0.2686,  1.2466,  2.3522],
         [ 1.5607, -2.9683,  0.2349]],

        [[-0.8316, -1.1493,  0.0612],
         [ 1.2385,  0.5432,  0.1464],
         [ 0.1538,  1.5263, -0.2739],
         [ 1.1321, -0.5144,  1.8355],
         [ 0.5592,  0.4163,  1.7067],
         [ 2.5304, -1.0066,  0.2032]],

        [[ 0.9103, -0.8966,  0.8245],
         [-0.0280,  1.5550,  0.5115],
    

In [241]:
h[2:, 1].shape

torch.Size([3, 3])

In [242]:
h[2, 1].shape

torch.Size([3])

In [243]:
h[3, 0].reshape(1, 3).shape

torch.Size([1, 3])

In [244]:
torch.cat((h[3, 0].reshape(1, 3), h[2, 1].reshape(1, 3), h[2, 2].reshape(1, 3), h[4, 3].reshape(1, 3)), 0).shape

torch.Size([4, 3])

In [245]:
f_lens = [3, 2, 4, 1, 2, 3]

In [248]:
cat_list = [h[f_lens[m], m].reshape(1, 3) for m in range(6)]

In [252]:
forward = torch.cat(cat_list, 0)

In [253]:
forward.shape

torch.Size([6, 3])

In [255]:
backward = h[0]

In [256]:
backward.shape

torch.Size([6, 3])

In [258]:
torch.cat((forward, backward), 1).shape

torch.Size([6, 6])

In [261]:
embedding(torch.LongTensor([0,1,2,3]))

tensor([[-0.3574,  0.1658,  2.3912],
        [ 0.8635, -0.2714, -0.8179],
        [ 0.0000,  0.0000,  0.0000],
        [-0.1126,  0.2189,  0.7983]], grad_fn=<EmbeddingBackward>)

In [263]:
s = 9
m = 7
h = 5

In [264]:
htilde_t = torch.randn(7, 10)

In [265]:
h = torch.rand(9, 7, 10)

In [269]:
h.shape

torch.Size([9, 7, 10])

In [268]:
h[0].shape

torch.Size([7, 10])

In [294]:
cos = torch.nn.functional.cosine_similarity(h[0], htilde_t)

In [295]:
cos

tensor([-0.0726,  0.0067,  0.4042, -0.3562,  0.1158, -0.1761,  0.0590])

In [296]:
cos.shape

torch.Size([7])

In [275]:
htilde_t

tensor([[-1.0889,  0.6842, -1.3070,  0.1398, -0.9617, -0.1051, -0.4457,  0.0338,
         -0.4078,  1.5276],
        [-0.1923,  1.0502,  0.5184,  0.5928,  0.5360, -0.1974, -0.0122, -1.3333,
         -0.0234, -0.9229],
        [ 1.9786,  0.9311, -0.2502,  0.6432,  0.5058, -1.5719,  1.0076, -0.4781,
         -0.2290,  1.0992],
        [-0.9844,  0.1714, -0.8047, -1.2404, -0.3570, -0.0222,  1.2665,  0.8010,
         -1.8195, -1.6104],
        [ 1.1156, -0.6931, -0.5508,  2.7131, -0.2530,  0.0061, -0.1758,  0.9426,
          0.8677,  0.7886],
        [-2.2319, -0.4602, -0.7692,  1.4860, -0.1149,  0.0335, -0.5704,  0.2355,
          1.0106,  0.8452],
        [-0.1746,  1.1045, -1.8069,  0.0293, -0.1434, -0.3727,  0.0032,  1.3072,
          2.2941, -1.0775]])

In [288]:
h_tile = htilde_t.repeat(9, 1, 1)

In [289]:
h_tile.shape

torch.Size([9, 7, 10])

In [300]:
torch.nn.functional.cosine_similarity(h, h_tile, 2)

tensor([[-0.0726,  0.0067,  0.4042, -0.3562,  0.1158, -0.1761,  0.0590],
        [-0.3452,  0.0517,  0.2004, -0.5046,  0.4202,  0.1179, -0.1005],
        [ 0.1859,  0.1263,  0.4755, -0.3687,  0.5156, -0.2250,  0.2711],
        [-0.0778, -0.2428,  0.1834, -0.4791,  0.3097, -0.2025,  0.1658],
        [-0.0475,  0.1962,  0.1442, -0.2979,  0.2473, -0.0862,  0.0777],
        [-0.3053, -0.0237, -0.0541, -0.4194,  0.4098, -0.0283,  0.0428],
        [-0.4158,  0.0322,  0.4304, -0.1613,  0.4623,  0.2667,  0.0162],
        [-0.3504,  0.0578,  0.1923, -0.5112,  0.2647, -0.0661, -0.1296],
        [-0.2026, -0.3274,  0.4501, -0.3493,  0.4072,  0.2017,  0.0137]])

In [302]:
alpha_t = torch.randn(s, m)

In [303]:
h = torch.randn(s, m, 10)

In [309]:
a = torch.randn(2, 4, 3)

In [312]:
torch.sum(a, 0).shape

torch.Size([4, 3])

In [316]:
a = torch.randn(m, 3)

In [317]:
b = torch.randn(m, 1)

In [329]:
torch.cat([a, b], 1).shape

torch.Size([7, 4])

In [325]:
ct = torch.randn(s, m, 3)

In [326]:
ct.shape

torch.Size([9, 7, 3])

In [328]:
torch.sum(ct, dim=0).shape

torch.Size([7, 3])

In [347]:
hidden_state_size = 18

In [334]:
ct2 = torch.randn(m, hidden_state_size)

In [350]:
s, m, hidden_state_size

(9, 7, 18)

In [352]:
w = torch.nn.Linear(18, 18, bias=False)

In [353]:
wtilde = torch.nn.Linear(18, 18, bias=False)

In [354]:
h = torch.randn(s, m, hidden_state_size)

In [358]:
w(h).shape

torch.Size([9, 7, 18])

In [359]:
n = 6

In [369]:
split_n = w(h).view(s, m, n, -1)

In [375]:
w(h)[0][0]

tensor([ 0.5109, -0.0608,  0.1244,  0.3434,  0.2470, -0.1098,  0.3287,  0.5420,
         0.5583, -0.6204,  0.9697,  0.8861,  0.3634, -0.3308, -0.7573,  1.1626,
        -0.2869,  1.1272], grad_fn=<SelectBackward>)

In [374]:
split_n[0][0]

tensor([[ 0.5109, -0.0608,  0.1244],
        [ 0.3434,  0.2470, -0.1098],
        [ 0.3287,  0.5420,  0.5583],
        [-0.6204,  0.9697,  0.8861],
        [ 0.3634, -0.3308, -0.7573],
        [ 1.1626, -0.2869,  1.1272]], grad_fn=<SelectBackward>)

In [383]:
def get_energy_scores(htilde_t, h):
    s = h.shape[0]
    htilde_tile = htilde_t.repeat(s, 1, 1)
    e_t = torch.nn.functional.cosine_similarity(h, htilde_tile, 2)

    return e_t

In [384]:
def get_attention_weights(htilde_t, h, F_lens):
    e_t = get_energy_scores(htilde_t, h)
    pad_mask = torch.arange(h.shape[0], device=h.device)
    pad_mask = pad_mask.unsqueeze(-1) >= F_lens  # (S, M)
    e_t = e_t.masked_fill(pad_mask, -float('inf'))
    return torch.nn.functional.softmax(e_t, 0)

In [642]:
def attend(htilde_t, h, F_lens):
    alpha_t = get_attention_weights(htilde_t, h, F_lens)
    hidden_size = h.shape[2]
    # alpha_tile = alpha_t.repeat(1, 1, hidden_size)
    alpha_tile = torch.cat([alpha_t.unsqueeze(2) for i in range(hidden_size)], dim=2)
    c_s = alpha_tile * h
    c_t = torch.sum(c_s, dim=0)

    return c_t

In [522]:
htilde = torch.randn(m, hidden_state_size)

In [523]:
h = torch.randn(s, m, hidden_state_size)

In [524]:
f_lens = torch.randn(m, )

In [525]:
s = h.shape[0]

In [526]:
htilde_tile = htilde.repeat(s, 1, 1)

In [527]:
htilde_tile.shape

torch.Size([9, 7, 18])

In [530]:
e_t = torch.nn.functional.cosine_similarity(h, htilde_tile, 2)

In [531]:
pad_mask = torch.arange(h.shape[0], device=h.device)

In [533]:
pad_mask = pad_mask.unsqueeze(-1) >= f_lens  # (S, M)

In [536]:
e_t = e_t.masked_fill(pad_mask, -float('inf'))

In [538]:
alpha_t = torch.nn.functional.softmax(e_t, 0)

In [539]:
hidden_size = h.shape[2]

In [545]:
alpha_t.shape

torch.Size([9, 7])

In [565]:
alpha_t_3d = alpha_t.unsqueeze(2)

In [576]:
alpha_tile = torch.cat([alpha_t_3d for i in range(hidden_size)], dim=2)

In [583]:
c_s = (alpha_tile * h)

In [584]:
c_t = torch.sum(c_s, dim=0)

In [586]:
c_t.shape

torch.Size([7, 18])

In [588]:
attend(htilde, h, f_lens).shape

torch.Size([9, 7, 18])

In [612]:
embedding = torch.nn.Embedding(10, 3)

In [613]:
embedding(torch.LongTensor([[1,2,4,5],[4,3,2,9]]))

tensor([[[-0.5187, -0.3454, -0.9590],
         [ 2.2178, -0.0410,  0.1973],
         [ 1.4882, -0.9983,  1.0880],
         [-0.8400,  0.5552, -0.0591]],

        [[ 1.4882, -0.9983,  1.0880],
         [-0.3524,  0.3883,  0.0916],
         [ 2.2178, -0.0410,  0.1973],
         [-0.1704,  0.8797,  0.1297]]], grad_fn=<EmbeddingBackward>)

In [626]:
tens = torch.randn(m, hidden_size)

In [631]:
w(tens).view(m, hidden_size // n, n).shape

torch.Size([7, 3, 6])

In [628]:
n = 6

In [632]:
h_tens = torch.randn(s, m, hidden_size)

In [634]:
w(h_tens).view(s, m, hidden_size // n, n).shape

torch.Size([9, 7, 3, 6])

In [643]:
attend(tens, h_tens, f_lens).shape

torch.Size([7, 18])

In [668]:
htilde_w = w(tens)
h_w = w(h_tens)

In [669]:
htilde_w.shape

torch.Size([7, 18])

In [670]:
h_w.shape

torch.Size([9, 7, 18])

In [676]:
htilde_w.repeat_interleave(6).view(7, -1).shape

torch.Size([7, 108])

In [677]:
htilde_all = w(tens).repeat_interleave(n).view(m, -1)

In [678]:
h_all = w(h_tens).repeat_interleave(n).view(s, m, -1)

In [688]:
htilde_w.view(m, n, -1).shape

torch.Size([7, 6, 3])

In [690]:
htilde_w.view(m, n, -1)[:, 0, :].shape

torch.Size([7, 3])

In [697]:
attend(htilde_w.view(m, n, -1)[:, 0, :], h_w.view(s, m, n, -1)[:, :, 0, :], f_lens)

tensor([[-1.2084,  0.4211, -0.4742],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan],
        [-0.0710, -0.1596, -0.3749],
        [-0.3545, -0.5287, -0.1228],
        [    nan,     nan,     nan],
        [ 0.5195,  0.2079,  0.4796]], grad_fn=<SumBackward1>)

In [701]:
attend(htilde_w.view(m, n, -1)[:, 1, :], h_w.view(s, m, n, -1)[:, :, 1, :], f_lens)

tensor([[ 0.0181,  0.1368, -0.5476],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan],
        [-0.1795, -0.0950, -0.5661],
        [-0.5841, -0.1231,  1.2623],
        [    nan,     nan,     nan],
        [ 1.3810,  0.3875, -0.5613]], grad_fn=<SumBackward1>)

In [723]:
attend(htilde_all, h_all, f_lens).view(7, -1, 6, 1)[:, :, 0, 0]

tensor([[-1.2084,  0.4211, -0.4742,  0.0181,  0.1368, -0.5476, -1.0109, -0.3031,
         -1.0045, -0.1836,  1.0519, -0.4609,  0.9459,  0.0703, -1.1662, -1.3318,
          0.7634, -0.0167],
        [    nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
             nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
             nan,     nan],
        [    nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
             nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
             nan,     nan],
        [-0.0616, -0.1614, -0.3715, -0.1436, -0.0953, -0.6199,  0.5822,  0.0774,
         -0.5749, -0.0725, -0.8755,  0.5073, -0.1532, -0.8698, -0.3502,  0.3777,
         -0.3879,  0.0454],
        [-0.3545, -0.5287, -0.1228, -0.5841, -0.1231,  1.2623, -0.0689,  0.6637,
         -0.0287,  0.1588,  0.2769, -0.6577,  0.2495,  0.7494,  0.7414,  0.5287,
         -0.0849,  0.4527],
        [    nan,     nan,     nan,     nan,     n

In [726]:
torch.zeros_like(h).shape

torch.Size([9, 7, 18])

In [727]:
e = torch.randn(11, 9)

In [729]:
e.shape[0]

11

In [731]:
e[0].shape

torch.Size([9])

In [736]:
m0, v0 = 3, 5

In [740]:
logit1 = torch.randn(m0, v0)
logit2 = torch.randn(m0, v0)
logit3 = torch.randn(m0, v0)
logit4 = torch.randn(m0, v0)

In [741]:
logits = [logit1, logit2, logit3, logit4]

In [746]:
stack = torch.stack(logits, dim=0)

In [775]:
k, v = 2, 3

In [776]:
logpb_tm1 = torch.randn(m, k)
logpy_t = torch.randn(m, k, v)

In [777]:
logpb_tm1.unsqueeze(-1).shape

torch.Size([7, 2, 1])

In [778]:
logpy_t.shape

torch.Size([7, 2, 3])

In [779]:
(logpb_tm1.unsqueeze(-1) + logpy_t).squeeze(1).shape

torch.Size([7, 2, 3])

In [780]:
k0 = 1

In [849]:
logpb_tm1_0 = torch.randn(m, k0)
logpy_t_0 = torch.randn(m, k0, v)

In [850]:
(logpb_tm1_0.unsqueeze(-1) + logpy_t_0).squeeze(1).shape

torch.Size([7, 3])

In [851]:
extension_t = (logpb_tm1.unsqueeze(-1) + logpy_t)
extension_t_0 = (logpb_tm1_0.unsqueeze(-1) + logpy_t_0).squeeze(1)

In [852]:
extension_t.shape, extension_t_0.shape  # (M, K, V), (M, V)

(torch.Size([7, 2, 3]), torch.Size([7, 3]))

In [853]:
extension_t_0  # (M, V)

tensor([[ 0.1226,  0.3224,  0.8259],
        [ 0.1573,  1.6500,  1.0526],
        [-1.5815,  0.4779, -0.2466],
        [ 1.2344, -0.4485,  0.5280],
        [-0.3114,  0.0713,  0.7622],
        [ 0.8541, -0.1755, -0.4628],
        [-1.3359,  0.1081,  0.6300]])

In [854]:
extension_t_0.max(1)

torch.return_types.max(
values=tensor([0.8259, 1.6500, 0.4779, 1.2344, 0.7622, 0.8541, 0.6300]),
indices=tensor([2, 1, 1, 0, 2, 0, 2]))

In [799]:
a0, b0 = extension_t_0.max(1)
a0.shape

torch.Size([7])

In [861]:
extension_t.shape

torch.Size([7, 2, 3])

In [870]:
a, b = torch.topk(extension_t, k, dim=1)

In [871]:
b.shape

torch.Size([7, 2])

In [867]:
torch.flatten(extension_t, 1).shape

torch.Size([7, 6])

In [868]:
extension_t = torch.flatten(extension_t, 1)

In [869]:
extension_t.shape

torch.Size([7, 6])

In [872]:
b

tensor([[1, 0],
        [4, 5],
        [2, 0],
        [4, 3],
        [3, 1],
        [1, 5],
        [1, 0]])

In [823]:
b.shape

torch.Size([7, 2])

In [825]:
b.unsqueeze(0).shape

torch.Size([1, 7, 2])

In [826]:
btm1 = torch.randint(3, (2, m, k))

In [837]:
torch.cat([btm1, b.unsqueeze(0)], dim=0).shape

torch.Size([3, 7, 2])

In [841]:
et = torch.randn(7, 2, 3)

In [848]:
et[0].shape

torch.Size([2, 3])

In [873]:
c = torch.randint(6, (2, 3))

In [874]:
c

tensor([[5, 4, 2],
        [4, 0, 4]])

In [879]:
(c // 2).unsqueeze(-1).shape

torch.Size([2, 3, 1])

In [886]:
d = torch.randn(3, 2, 2)

In [887]:
d.shape

torch.Size([3, 2, 2])

In [889]:
torch.flatten(d, 1)

tensor([[ 1.1261, -0.4628, -1.6631, -0.5638],
        [-1.0850, -0.1095, -0.2923,  0.6784],
        [-0.0806, -1.1065, -0.2662,  0.7635]])

In [894]:
d.view(d.shape[0], -1) 

tensor([[ 1.1261, -0.4628, -1.6631, -0.5638],
        [-1.0850, -0.1095, -0.2923,  0.6784],
        [-0.0806, -1.1065, -0.2662,  0.7635]])

In [896]:
extension_t.shape

torch.Size([7, 6])

In [898]:
a1, b1 = torch.topk(extension_t, k, dim=1)

In [899]:
a2, b2 = extension_t.topk(k, -1, largest=True, sorted=True)

In [905]:
b2 = torch.remainder(b2, 3)

In [906]:
b2

tensor([[1, 0],
        [1, 2],
        [2, 0],
        [1, 0],
        [0, 1],
        [1, 2],
        [1, 0]])

In [909]:
eref = torch.LongTensor(5, 6)

In [917]:
eref.T.tolist()

[[34, 140629616532744, 570490880, 0, 4374027760],
 [0, 140629616532744, 0, 0, 3833126228550759937],
 [0, 140629616532784, 140629616532808, 0, 1],
 [0, 0, 140629616532808, 4374034400, 72058693549555713],
 [0, 29, 140629616532848, 0, -2305843009213693952],
 [0, 0, 1, 1, -2305843009213693952]]

In [916]:
eref.permute(1, 0).tolist()

[[34, 140629616532744, 570490880, 0, 4374027760],
 [0, 140629616532744, 0, 0, 3833126228550759937],
 [0, 140629616532784, 140629616532808, 0, 1],
 [0, 0, 140629616532808, 4374034400, 72058693549555713],
 [0, 29, 140629616532848, 0, -2305843009213693952],
 [0, 0, 1, 1, -2305843009213693952]]

In [920]:
f_lens - 1

tensor([-0.6852, -1.2624, -1.6081,  0.7777, -0.4969, -1.1036, -0.5613])

In [923]:
h = 6

In [924]:
eh = torch.randn(s, m, 2 * h)

In [934]:
ef = torch.LongTensor(m, )

In [926]:
mid = eh.shape[2] // 2

In [935]:
eh[ef - 1, torch.arange(ef.shape[0], device=eh.device), :mid]

IndexError: index -2305843009213693953 is out of bounds for dimension 0 with size 9

In [938]:
eh.shape

torch.Size([9, 7, 12])

In [940]:
eh[5:, 3].shape

torch.Size([4, 12])

In [948]:
eh[torch.tensor([2, 2, 2, 2, 2, 2, 2]), [i for i in range(7)]].shape

torch.Size([7, 12])

In [950]:
forward = eh[:, :, :6]

In [951]:
forward.shape

torch.Size([9, 7, 6])

In [958]:
fl = torch.tensor([2, 2, 2, 2, 2, 2, 2]) + 1
time = [i for i in range(7)]

In [959]:
forward[fl, time].shape

torch.Size([7, 6])

In [960]:
h = torch.tensor((s, m, 2 * h))

In [962]:
h = 6

In [965]:
h_tensor = torch.randn((s, m, 2 * h))

In [966]:
h_tensor.shape

torch.Size([9, 7, 12])

In [967]:
f_lens.shape

torch.Size([7])

In [968]:
hidden_size = h_tensor.shape[2]
m = h_tensor.shape[1]
htilde_0 = torch.zeros([m, hidden_size], device=h_tensor.device)

In [970]:
htilde_02 = torch.zeros_like(h_tensor[0], device=h_tensor.device)

In [974]:
torch.equal(htilde_0, htilde_02)

True